import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
  DATABASE_URL: z.string().min(1),
  PORT: z.coerce.number().default(3001),
  ANTHROPIC_API_KEY: z.string().optional(),
  GEMINI_API_KEY: z.string().optional(),
  GOOGLE_API_KEY: z.string().optional(),
  GOOGLE_IMAGE_MODEL: z.string().default("gemini-3-pro-image-preview"),
  GOOGLE_IMAGE_ALLOW_FALLBACK: z.coerce.boolean().default(false),
  GOOGLE_IMAGE_FALLBACK_MODEL: z.string().optional(),
  APIFY_API_TOKEN: z.string().optional(),
  APIFY_ACTOR_GMAPS: z.string().default("compass/google-maps-scraper"),
  APIFY_ACTOR_GMAPS_REVIEWS: z.string().default("compass/google-maps-reviews-scraper"),
  APIFY_ACTOR_GSEARCH: z.string().default("apify/google-search-scraper"),
  APIFY_ACTOR_WEB: z.string().default("apify/website-content-crawler"),
  APIFY_ACTOR_TALABAT: z.string().optional(),
  APIFY_ACTOR_DELIVEROO: z.string().optional(),
  APIFY_ACTOR_CAREEM: z.string().optional(),
  NANOBANANA_API_KEY: z.string().optional(),
  NANOBANANA_API_URL: z.preprocess((v) => (v === "" ? undefined : v), z.string().url().optional()),
  R2_ACCOUNT_ID: z.string().optional(),
  R2_ACCESS_KEY_ID: z.string().optional(),
  R2_SECRET_ACCESS_KEY: z.string().optional(),
  R2_BUCKET_NAME: z.string().default("bustan"),
  R2_PUBLIC_URL: z.string().url().default("https://images.getbustan.com"),
  CLERK_SECRET_KEY: z.string().optional(),
  CLERK_JWT_KEY: z.string().optional(),
  CLERK_JWT_ISSUER: z.string().optional(),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  BACKEND_WEBHOOK_SYNC_SECRET: z.string().min(32).optional(),
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: z.string().min(16).optional(),
  WHATSAPP_TOKEN_ENCRYPTION_KEY: z.string().min(32).optional(),
  META_APP_ID: z.string().optional(),
  META_APP_SECRET: z.string().optional(),
  META_WHATSAPP_CONFIG_ID: z.string().optional(),
  META_GRAPH_API_VERSION: z.string().default("v24.0"),
  STRIPE_STARTER_PRICE_ID: z.string().optional(),
  STRIPE_PRO_PRICE_ID: z.string().optional(),
  STRIPE_PORTFOLIO_PRICE_ID: z.string().optional(),
  STRIPE_TRIAL_DAYS: z.coerce.number().int().positive().default(14),
  RESEND_API_KEY: z.string().optional(),
  RESEND_FROM_EMAIL: z.string().email().optional(),
  FRONTEND_APP_URL: z.string().url().default("http://localhost:3000"),
});

export const env = envSchema.parse(process.env);
