import type { CreativeArchetype } from "./types";

// =============================================================================
// 22 WINNING RESTAURANT AD CREATIVE ARCHETYPES (Q2 2026)
// =============================================================================
//
// Universal 2026 truths governing all archetypes:
// - 7-30 sec is performance sweet spot; 20 sec with emotional hook in first 3 sec is Ramadan/UAE optimum
// - Raw, lo-fi, phone-shot content out-converts polished studio content
// - DM share is now #1 Reels ranking signal (worth ~15 likes); design endings that trigger "send to friend"
// - Sound-on is the goal but ~50% watch muted — every archetype must work with text overlays only
// - Hashtag cap is 5 on Instagram (Dec 2025); intent-based hashtags only
//
// Each archetype is implementable as a structured prompt template for the AI generator.

export const creativeArchetypes: CreativeArchetype[] = [
  {
    id: "cheese_pull_money_shot",
    name: "Cheese Pull / Money Shot",
    why: "Hard-wired sensory craving + curiosity gap (how far will it stretch?). Credited with measurably driving foot traffic to chain restaurants per NPR Dec 2025.",
    bRollShots: [
      "Macro close-up of cheese/sauce/yolk separating, slowed 50-80%",
      "Secondary plate-context shot",
      "Finishing bite shot",
    ],
    durationSec: { min: 7, max: 12 },
    editingRhythm: ["single_take"],
    sound: ["asmr"],
    textOverlay: "Single line, top-third, e.g. 'The pull at [Restaurant]'. No more.",
    ctaPattern: "End-card with dish name + branch name; caption-only soft CTA",
    bestPlatforms: ["meta_reels", "tiktok_in_feed", "meta_stories"],
    cuisineFits: ["pizza", "kunafa", "manakish", "lebanese", "casual"],
    funnelStages: ["tofu"],
    failureModes: [
      "Stretch breaks too early",
      "Awkward hand position",
      "Hot lighting flattens texture",
      "Over-cut destroys dopamine arc",
    ],
    menaAdaptation: "Lean into kunafa cheese pulls, halloumi pulls, nashef-style sajiyah cheese, oozy molten knafeh. Pair with Arabic exclamation overlay (e.g. 'تشد!').",
  },
  {
    id: "pov_first_bite",
    name: "POV First Bite",
    why: "Vicarious eating, social proof, authentic reaction. POV hooks generate highest comment counts (Retiplex, Akselera 2026).",
    bRollShots: [
      "First-person hand reaching in",
      "Pickup of dish",
      "Bringing to camera",
      "Bite + eyes close + head tilt",
    ],
    durationSec: { min: 10, max: 15 },
    editingRhythm: ["single_take", "match_cut"],
    sound: ["trending_audio", "diegetic"],
    textOverlay: "'POV: you ordered the [dish] at [restaurant]'",
    ctaPattern: "Caption with map pin emoji + neighborhood",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["burger", "sushi", "shawarma", "dessert", "casual"],
    funnelStages: ["tofu", "mofu"],
    failureModes: ["Awkward angle", "Too dark", "Mouth-full talking"],
    menaAdaptation: "Use right hand only on camera. For shawarma/manousheh, capture wrap-and-bite single take. Avoid pork imagery entirely.",
  },
  {
    id: "behind_the_pass",
    name: "Behind-the-Pass / Kitchen Ballet",
    why: "Authenticity premium. Behind-the-scenes humanizes brand; trust signal (Otter, Versacreative 2026).",
    bRollShots: [
      "Wide shot of pass",
      "3 close-ups of plating actions",
      "1 chef's-hands macro",
      "1 ticket flying in",
      "Sizzle on grill",
    ],
    durationSec: { min: 15, max: 25 },
    editingRhythm: ["fast_cut_8_12", "whip_pan"],
    sound: ["trending_audio", "diegetic", "music_underscore"],
    textOverlay: "None or single time-stamp ('Friday 9:47 PM, table 14')",
    ctaPattern: "End frame: 'Reserve a counter seat — link in bio.'",
    bestPlatforms: ["meta_reels", "tiktok_in_feed", "youtube_shorts"],
    cuisineFits: ["fine_dining", "premium_casual", "casual"],
    funnelStages: ["tofu", "mofu"],
    failureModes: ["Looks staged", "Chefs glance at camera", "Messy frame"],
    menaAdaptation: "Show grill-master skill on charcoal mishwi/mandi/ouzi; avoid alcohol bottles in shot if family-positioned.",
  },
  {
    id: "founder_origin",
    name: "Founder / Origin Story",
    why: "Narrative empathy. Drives saves and DMs because it converts brand into character.",
    bRollShots: [
      "Owner walking into restaurant",
      "Hand on memento",
      "Family photo",
      "First dish prep",
      "Voiceover-driven cuts",
    ],
    durationSec: { min: 45, max: 90 },
    editingRhythm: ["match_cut"],
    sound: ["voiceover_real", "music_underscore"],
    textOverlay: "Subtitled voiceover, bilingual",
    ctaPattern: "'Come meet us. [address].'",
    bestPlatforms: ["meta_reels", "youtube_shorts"],
    cuisineFits: ["lebanese", "egyptian", "khaleeji", "cafe", "fine_dining", "premium_casual"],
    funnelStages: ["tofu", "mofu"],
    failureModes: ["Over-scripted", "Corporate tone", "Founder reads from card"],
    menaAdaptation: "Strong fit — heritage/multi-generation framing resonates ('teta's recipe', 'since 1972 in Aleppo'). Use Arabic VO with English subtitles.",
  },
  {
    id: "hidden_gem_reveal",
    name: "Hidden Gem Reveal",
    why: "Curiosity gap + locality flex. 'Insider' framing makes viewers want to share.",
    bRollShots: [
      "Walking-in POV from street",
      "Door open",
      "Neon",
      "Signature dish reveal",
    ],
    durationSec: { min: 10, max: 15 },
    editingRhythm: ["match_cut"],
    sound: ["trending_audio"],
    textOverlay: "'Nobody talks about this place in [neighborhood]…'",
    ctaPattern: "Map pin + name in caption",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["streetfood", "casual"],
    funnelStages: ["tofu"],
    failureModes: ["Place looks too polished — kills 'hidden' claim"],
    menaAdaptation: "Old Dubai, Deira, Karama, Satwa, Mirdif backstreets, Souq Waqif, Al Khobar Corniche — lean into neighborhood pride.",
  },
  {
    id: "speed_run_60s",
    name: "Order in 60 Seconds (Speed Run)",
    why: "Curiosity + completion satisfaction. Loops well. Pairs with delivery promise.",
    bRollShots: [
      "Order placed",
      "Kitchen action",
      "Plating",
      "Table",
      "Bite",
      "Timer overlay throughout",
    ],
    durationSec: { min: 30, max: 60 },
    editingRhythm: ["match_cut", "fast_cut_8_12"],
    sound: ["trending_audio", "music_underscore"],
    textOverlay: "Live timer, dish name on plate-down",
    ctaPattern: "'Open daily 12 PM – 1 AM.'",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["qsr", "shawarma", "pizza", "burger"],
    funnelStages: ["bofu"],
    failureModes: ["Timer feels gimmicky", "Cuts hide the real time"],
    menaAdaptation: "Pair with delivery angle — Talabat / Careem / Deliveroo timer.",
  },
  {
    id: "day_in_life_chef",
    name: "Day in the Life of a Chef",
    why: "Parasocial bond, behind-the-curtain.",
    bRollShots: [
      "5 AM market run",
      "Prep",
      "Pass",
      "Post-service tea/walk",
      "Lock-up",
    ],
    durationSec: { min: 60, max: 90 },
    editingRhythm: ["match_cut"],
    sound: ["voiceover_real", "music_underscore"],
    textOverlay: "Time stamps ('4:47 AM — fish market')",
    ctaPattern: "'Tasting menu — Wed–Sat.'",
    bestPlatforms: ["youtube_shorts", "meta_reels"],
    cuisineFits: ["fine_dining", "premium_casual"],
    funnelStages: ["mofu"],
    failureModes: ["Reads like a CV reel"],
    menaAdaptation: "Show souq run (Waterfront Market Dubai, Al Aweer), camel/lamb butcher visit, mosque break for adhan; locally-sourced sticker.",
  },
  {
    id: "locals_menu_hack",
    name: "Locals' Menu Hack",
    why: "Insider secret + how-to value = save-bait.",
    bRollShots: [
      "Customer ordering",
      "Off-menu item appearing",
      "Reaction",
    ],
    durationSec: { min: 15, max: 25 },
    editingRhythm: ["match_cut"],
    sound: ["trending_audio"],
    textOverlay: "'Most people order X. Order Y instead.'",
    ctaPattern: "'Tell a friend.'",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    failureModes: ["'Hack' is just a regular menu item — feels dishonest"],
    menaAdaptation: "'Ask the waiter for the Lebanese arabic menu' (hidden mezze board); off-menu shisha flavors; Friday brunch upgrade.",
  },
  {
    id: "asmr_sizzle",
    name: "ASMR Sizzle",
    why: "Pure sensory; mute-friendly AND sound-on; high completion.",
    bRollShots: [
      "Sear hitting pan",
      "Knife on board",
      "Pour",
      "Sprinkle",
      "Sizzle",
      "Slice (4-6 close mic'd action moments)",
    ],
    durationSec: { min: 10, max: 20 },
    editingRhythm: ["single_take", "match_cut"],
    sound: ["asmr"],
    textOverlay: "Minimal. Maybe dish name.",
    ctaPattern: "Caption-only",
    bestPlatforms: ["meta_reels", "tiktok_in_feed", "youtube_shorts"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    failureModes: ["Bad mic", "Environmental noise", "Cuts that break audio illusion"],
    menaAdaptation: "Charcoal sizzle on mishwi, sajj manakish on hot dome, kunafa sugar pour, qahwa pour into finjan.",
  },
  {
    id: "stop_motion_build_up",
    name: "Stop-Motion Dish Build-Up",
    why: "Highly shareable, satisfying, distinctive.",
    bRollShots: ["Static overhead camera; 40-80 frames built one ingredient at a time"],
    durationSec: { min: 10, max: 15 },
    editingRhythm: ["stop_motion"],
    sound: ["trending_audio", "music_underscore"],
    textOverlay: "Final dish name appears at end",
    ctaPattern: "End frame logo + dish",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["mezze", "pizza", "casual"],
    funnelStages: ["tofu"],
    failureModes: ["Camera shifts", "Lighting changes", "Uneven ingredient timing"],
    menaAdaptation: "Mezze spread build-up is iconic for this format; mandi/ouzi platter assembly.",
  },
  {
    id: "side_by_side_taste_test",
    name: "Side-by-Side Taste Test",
    why: "Comparison engages; brand looks confident.",
    bRollShots: ["Two dishes", "Tasters", "Reaction", "Final pick"],
    durationSec: { min: 20, max: 30 },
    editingRhythm: ["split_screen"],
    sound: ["voiceover_real", "trending_audio"],
    textOverlay: "Labels A and B",
    ctaPattern: "'Try both at [restaurant].'",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["burger", "kunafa", "mandi", "indian"],
    funnelStages: ["mofu"],
    failureModes: ["Comparing your dish to a competitor by name (legal risk)"],
    menaAdaptation: "'Beirut vs. Damascus knafeh', 'Yemeni vs. Saudi mandi' — celebrate regional variations.",
  },
  {
    id: "customer_reaction",
    name: "Customer Reaction (Reaction-Cam)",
    why: "Social proof, real surprise = trust.",
    bRollShots: ["Hidden-friendly fixed camera on table; permission obtained; first bite captured"],
    durationSec: { min: 10, max: 15 },
    editingRhythm: ["single_take"],
    sound: ["diegetic"],
    textOverlay: "'First time at [Restaurant]'",
    ctaPattern: "Caption",
    bestPlatforms: ["meta_reels", "tiktok_in_feed", "meta_stories"],
    cuisineFits: ["all", "dessert"],
    funnelStages: ["mofu"],
    failureModes: ["No release/consent (legal)", "Reactions look acted"],
    menaAdaptation: "Always get explicit verbal + written consent; do not film children's faces; respect hijab/niqab privacy norms — frame to hands and dish only when uncertain.",
  },
  {
    id: "texture_close_up_loop",
    name: "Texture Close-Up Loop",
    why: "Hypnotic, loops infinitely → high completion = algorithmic boost.",
    bRollShots: ["One macro shot, looping action (ladle dipping, dough stretching, sauce drizzling)"],
    durationSec: { min: 5, max: 8 },
    editingRhythm: ["single_take"],
    sound: ["asmr"],
    textOverlay: "None (preserve hypnotic effect)",
    ctaPattern: "Caption only",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all", "dessert", "kunafa"],
    funnelStages: ["tofu"],
    failureModes: ["Visible loop seam", "Changes in lighting or focus"],
    menaAdaptation: "Karak chai pour loop, kunafa syrup, tahini drizzle, dripping honey on awameh.",
  },
  {
    id: "trend_audio_match_cut",
    name: "Trend Audio Match-Cut",
    why: "Algorithmic boost from trending audio (5K-50K uses sweet spot per Versacreative 2026).",
    bRollShots: ["4-6 cuts of food/restaurant matched to audio beats"],
    durationSec: { min: 7, max: 15 },
    editingRhythm: ["match_cut", "fast_cut_8_12"],
    sound: ["trending_audio"],
    textOverlay: "Optional caption-style; do not cover faces of foods",
    ctaPattern: "Caption-only",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    failureModes: ["Audio peaks past trend", "Using copyrighted music in PAID ads (must use commercial library)"],
    menaAdaptation: "Watch Arab TikTok trends specifically — they cycle separately from US/EU. Khaleeji music, Arabic comedy clips, Egyptian sound bites perform well regionally.",
  },
  {
    id: "streetfood_walking_pov",
    name: "Streetfood Walking POV",
    why: "Immersive, escapist, 'I'm there'.",
    bRollShots: [
      "Gimbal walk through alley/souq",
      "Vendor",
      "Dish handed to camera",
      "Bite",
    ],
    durationSec: { min: 20, max: 40 },
    editingRhythm: ["single_take"],
    sound: ["diegetic"],
    textOverlay: "Final card with location name + price",
    ctaPattern: "Pin in caption",
    bestPlatforms: ["meta_reels", "tiktok_in_feed", "youtube_shorts"],
    cuisineFits: ["streetfood"],
    funnelStages: ["tofu"],
    failureModes: ["Shaky cam", "Nausea-inducing"],
    menaAdaptation: "Souq Waqif Doha, Old Dubai spice souq, Riyadh Boulevard, Al Khobar Corniche, Mahalat — shisha walks at night.",
  },
  {
    id: "what_i_eat_in_a_day",
    name: "What I Eat in a Day at [Restaurant]",
    why: "Listicle structure + parasocial = saves.",
    bRollShots: ["3-5 dishes, each with one hero shot + bite"],
    durationSec: { min: 30, max: 45 },
    editingRhythm: ["match_cut"],
    sound: ["voiceover_real", "trending_audio"],
    textOverlay: "Dish 1, Dish 2, Dish 3 title cards",
    ctaPattern: "'Full menu in bio.'",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["cafe", "brunch", "casual"],
    funnelStages: ["mofu"],
    failureModes: ["Too many dishes, no edit"],
    menaAdaptation: "'What I eat from suhoor to iftar' Ramadan version is gold.",
  },
  {
    id: "before_after_plating",
    name: "Before/After Plating Transformation",
    why: "Transformation = dopamine; shareable.",
    bRollShots: ["Raw ingredient → finished plate with smooth transition"],
    durationSec: { min: 7, max: 12 },
    editingRhythm: ["match_cut", "whip_pan"],
    sound: ["trending_audio"],
    textOverlay: "'Before / After' or none",
    ctaPattern: "End-frame logo",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    failureModes: ["Transition too obvious", "Cheesy zoom"],
    menaAdaptation: "Whole lamb → ouzi platter; raw dough → manousheh from sajj; raw kunafa pan → flipped plate.",
  },
  {
    id: "ingredient_provenance",
    name: "Ingredient Provenance Story",
    why: "Premium signal; 'why we cost what we cost.'",
    bRollShots: ["Farm/sea/market footage", "Kitchen", "Plate"],
    durationSec: { min: 20, max: 30 },
    editingRhythm: ["match_cut"],
    sound: ["voiceover_real", "music_underscore"],
    textOverlay: "Captions for sourcing line",
    ctaPattern: "'Limited supply, weekends only.'",
    bestPlatforms: ["meta_reels", "youtube_shorts"],
    cuisineFits: ["fine_dining", "premium_casual"],
    funnelStages: ["mofu"],
    failureModes: ["Stock footage = death of trust"],
    menaAdaptation: "Omani lamb, Hammour from Khor Fakkan, Ras al Khaimah dates, Saudi black-bee honey, Lebanese olive oil — local provenance is a strong premium signal.",
  },
  {
    id: "empty_plate_review",
    name: "Empty Plate Review",
    why: "Inverse review; visual proof.",
    bRollShots: ["Plate covered", "Eating montage", "Empty plate"],
    durationSec: { min: 10, max: 15 },
    editingRhythm: ["time_lapse"],
    sound: ["trending_audio"],
    textOverlay: "'Best review I've ever written.'",
    ctaPattern: "Caption",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["casual", "premium_casual", "mandi"],
    funnelStages: ["mofu"],
    failureModes: ["Looks gross if not lit well"],
    menaAdaptation: "Lamb mandi cleared to bones; mezze platter swept clean.",
  },
  {
    id: "late_night_craving_skit",
    name: "Late-Night Craving Skit",
    why: "Relatable + comedic = shares.",
    bRollShots: ["Person on couch, scroll, dish appears"],
    durationSec: { min: 15, max: 25 },
    editingRhythm: ["match_cut"],
    sound: ["voiceover_real", "trending_audio"],
    textOverlay: "Subtitled dialogue",
    ctaPattern: "'Open until 4 AM, delivery via [partner].'",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["qsr", "cafe", "shisha"],
    funnelStages: ["bofu"],
    failureModes: ["Acting feels forced", "Humor lost in translation"],
    menaAdaptation: "Post-Tarawih craving (Ramadan), 2 AM karak run, post-shisha dessert — high cultural resonance.",
  },
  {
    id: "family_table_reveal",
    name: "Group / Family Table Reveal",
    why: "Aspirational social proof + portion impact. HIGHEST-PERFORMING archetype for GCC family audiences.",
    bRollShots: [
      "Empty table",
      "Servers laying down spread",
      "Wide reveal",
      "Group hands reaching",
    ],
    durationSec: { min: 12, max: 20 },
    editingRhythm: ["time_lapse", "fast_cut_8_12"],
    sound: ["trending_audio", "music_underscore"],
    textOverlay: "'Family-of-6 set — AED 299'",
    ctaPattern: "'Reserve via WhatsApp +971…'",
    bestPlatforms: ["meta_reels", "meta_stories", "meta_feed", "snapchat_story_ad"],
    cuisineFits: ["mandi", "mezze", "khaleeji", "lebanese", "indian", "premium_casual"],
    funnelStages: ["bofu"],
    failureModes: ["Table too messy/cluttered", "Harsh top-down lighting"],
    menaAdaptation: "Iftar tables, ouzi platters, mandi feast, Khaleeji majlis spreads. The default Ramadan creative.",
  },
  {
    id: "hand_reach_pickup",
    name: "Hand Reach + Single-Take Pickup",
    why: "'Human hand reaching' boosts CTR (food-photo industry rule); creates intimacy.",
    bRollShots: [
      "Static camera on dish",
      "Hand enters frame",
      "Lifts a piece",
      "Pulls back",
    ],
    durationSec: { min: 5, max: 8 },
    editingRhythm: ["single_take"],
    sound: ["asmr"],
    textOverlay: "None",
    ctaPattern: "Caption",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["pizza", "manakish", "mezze"],
    funnelStages: ["tofu"],
    failureModes: ["Wrong hand culturally", "Chipped nails", "Smudged glassware visible"],
    menaAdaptation: "Right hand only on camera; bare wrist (no watch logo); women's hands with henna fit traditional cuisine; bare male wrist for streetfood/grill.",
  },
];

// =============================================================================
// DECISION RULES — for the AI generator to pick archetypes given a brief
// =============================================================================

export const archetypeDecisionRules = {
  byGoalAndBudget: {
    awareness_low_budget: ["cheese_pull_money_shot", "asmr_sizzle", "texture_close_up_loop", "before_after_plating", "hand_reach_pickup"],
    consideration: ["pov_first_bite", "hidden_gem_reveal", "day_in_life_chef", "what_i_eat_in_a_day", "ingredient_provenance", "side_by_side_taste_test"],
    conversion: ["speed_run_60s", "family_table_reveal", "late_night_craving_skit"],
  },
  byCuisine: {
    fine_dining: ["behind_the_pass", "founder_origin", "day_in_life_chef", "ingredient_provenance"],
    streetfood: ["hidden_gem_reveal", "streetfood_walking_pov", "empty_plate_review", "late_night_craving_skit"],
    family_casual: ["family_table_reveal", "what_i_eat_in_a_day", "customer_reaction", "late_night_craving_skit"],
    qsr_delivery: ["speed_run_60s", "asmr_sizzle", "late_night_craving_skit"],
    cafe_dessert: ["asmr_sizzle", "texture_close_up_loop", "stop_motion_build_up", "what_i_eat_in_a_day"],
  },
  bySeason: {
    ramadan: {
      mandatoryArchetypes: ["family_table_reveal"],
      preferredArchetypes: ["pov_first_bite", "ingredient_provenance", "what_i_eat_in_a_day", "founder_origin"],
      forbiddenArchetypes: [], // No archetype is forbidden, but pacing changes.
      timingNotes: "Post-Iftar 8-11 PM optimal posting; Suhoor late-night (11pm-2am) also peaks",
    },
    eid: {
      mandatoryArchetypes: ["family_table_reveal"],
      preferredArchetypes: ["before_after_plating", "what_i_eat_in_a_day"],
      forbiddenArchetypes: [],
    },
    summer_uae_ksa: {
      preferredArchetypes: ["asmr_sizzle", "speed_run_60s", "late_night_craving_skit"],
      forbiddenArchetypes: [],
      timingNotes: "Indoor only; deliveries surge 1-3pm and 7-10pm",
    },
  },
  byKhaleejiAudience: {
    requireArabicOverlays: true,
    preferredArchetypes: ["family_table_reveal", "founder_origin", "ingredient_provenance"],
    avoidArchetypes: ["late_night_craving_skit"], // Too informal for premium Khaleeji
    notes: "Always Arabic-on-top captions for KSA/conservative regions",
  },
} as const;
