import type { CtaPattern } from "./types";

// =============================================================================
// CTA LIBRARY — 32 patterns by intent (Q2 2026)
// =============================================================================

export const ctaPatterns: CtaPattern[] = [
  // -------------------------------------------------------------------------
  // RESERVE / BOOK
  // -------------------------------------------------------------------------
  {
    id: "reserve_a_table",
    intent: "reserve",
    english: "Reserve a table",
    arabic: "احجز طاولتك",
    bestPlatforms: ["meta_feed", "meta_reels", "google_search"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Evergreen",
  },
  {
    id: "book_your_spot",
    intent: "reserve",
    english: "Book your spot",
    arabic: "احجز مكانك",
    bestPlatforms: ["tiktok_in_feed", "meta_stories"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Casual feel — fits Gen Z",
  },
  {
    id: "tap_to_book",
    intent: "reserve",
    english: "Tap to book",
    arabic: "اضغط للحجز",
    bestPlatforms: ["meta_reels", "meta_stories", "tiktok_in_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Mobile-native, evergreen",
  },
  {
    id: "whatsapp_to_reserve",
    intent: "reserve",
    english: "WhatsApp to reserve",
    arabic: "احجز عبر واتساب",
    bestPlatforms: ["meta_feed", "meta_reels", "meta_stories", "meta_ctwa"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Highest CVR in MENA — default for UAE/GCC",
  },
  {
    id: "last_seats_book",
    intent: "reserve",
    english: "Last 4 seats — book",
    arabic: "آخر ٤ مقاعد - احجز",
    bestPlatforms: ["meta_stories", "meta_reels"],
    funnelStages: ["bofu"],
    fatigue: "moderate",
    notes: "Burns out fast (4 weeks); rotate scarcity number",
  },
  {
    id: "dm_table_to_book",
    intent: "reserve",
    english: 'DM "table" to book',
    arabic: 'راسلنا "طاولة"',
    bestPlatforms: ["meta_reels"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "IG-organic strong; works less for paid (Manychat API limit cut to 200/hr in 2026)",
  },

  // -------------------------------------------------------------------------
  // ORDER DELIVERY
  // -------------------------------------------------------------------------
  {
    id: "order_now_talabat",
    intent: "order_delivery",
    english: "Order now on Talabat",
    arabic: "اطلب الآن من تلاباط",
    bestPlatforms: ["meta_feed", "meta_reels", "tiktok_in_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
  },
  {
    id: "delivered_tonight",
    intent: "order_delivery",
    english: "Get it delivered tonight",
    arabic: "وصلك الليلة",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
  },
  {
    id: "order_careem_food",
    intent: "order_delivery",
    english: "Order on Careem Food",
    arabic: "اطلب من كريم فود",
    bestPlatforms: ["meta_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
  },
  {
    id: "hot_in_25_min",
    intent: "order_delivery",
    english: "Hot in 25 minutes",
    arabic: "ساخن خلال ٢٥ دقيقة",
    bestPlatforms: ["meta_feed", "meta_reels"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Quantified promise outperforms vague 'fast delivery'",
  },
  {
    id: "skip_the_queue",
    intent: "order_delivery",
    english: "Skip the queue, order now",
    arabic: "تخطى الطابور",
    bestPlatforms: ["meta_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
  },

  // -------------------------------------------------------------------------
  // VISIT / DINE-IN
  // -------------------------------------------------------------------------
  {
    id: "pull_up_tonight",
    intent: "visit_dine_in",
    english: "Pull up tonight",
    arabic: "تعالوا الليلة",
    bestPlatforms: ["tiktok_in_feed", "meta_stories"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Younger audience tone",
  },
  {
    id: "open_till_1am",
    intent: "visit_dine_in",
    english: "Open till 1AM",
    arabic: "مفتوح حتى الواحدة فجراً",
    bestPlatforms: ["meta_feed", "meta_reels"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Late-night context",
  },
  {
    id: "walk_in_this_weekend",
    intent: "visit_dine_in",
    english: "Walk in this weekend",
    arabic: "تعالى نهاية الأسبوع",
    bestPlatforms: ["meta_feed", "meta_reels"],
    funnelStages: ["bofu"],
    fatigue: "low",
  },
  {
    id: "see_you_friday",
    intent: "visit_dine_in",
    english: "See you Friday",
    arabic: "نشوفك الجمعة",
    bestPlatforms: ["meta_reels", "meta_stories", "tiktok_in_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
  },
  {
    id: "drop_by_saved_seat",
    intent: "visit_dine_in",
    english: "Drop by, we saved you a seat",
    arabic: "تعال، لك مكان محجوز",
    bestPlatforms: ["meta_stories"],
    funnelStages: ["retention"],
    fatigue: "low",
    notes: "Retention/dormant reactivation",
  },

  // -------------------------------------------------------------------------
  // ENGAGE (TOFU/MOFU)
  // -------------------------------------------------------------------------
  {
    id: "dm_us_menu",
    intent: "engage",
    english: 'DM us "menu"',
    arabic: 'راسلنا "قائمة"',
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    funnelStages: ["mofu"],
    fatigue: "moderate",
    notes: "API rate-limit constrains this in 2026 (200/hr); use sparingly",
  },
  {
    id: "save_this_post",
    intent: "engage",
    english: "Save this post",
    arabic: "احفظ هذا المنشور",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    funnelStages: ["tofu"],
    fatigue: "low",
  },
  {
    id: "tag_who_to_bring",
    intent: "engage",
    english: "Tag who you'd bring",
    arabic: "علّم اللي حتجيبه معك",
    bestPlatforms: ["meta_reels", "meta_stories", "tiktok_in_feed"],
    funnelStages: ["tofu"],
    fatigue: "low",
    notes: "Drives the #1 Reels ranking signal (DM share)",
  },
  {
    id: "comment_your_order",
    intent: "engage",
    english: "Comment your order",
    arabic: "اكتب طلبك في التعليقات",
    bestPlatforms: ["tiktok_in_feed"],
    funnelStages: ["mofu"],
    fatigue: "low",
  },
  {
    id: "share_with_foodie",
    intent: "engage",
    english: "Share with the foodie friend",
    arabic: "شاركها مع صديق محب الأكل",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    funnelStages: ["tofu"],
    fatigue: "low",
  },
  {
    id: "send_to_owes_meal",
    intent: "engage",
    english: "Send this to whoever owes you a meal",
    arabic: "ابعتها لأي حد عليه عزومة",
    bestPlatforms: ["meta_reels"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Share-bait — strong DM signal",
  },

  // -------------------------------------------------------------------------
  // LEAD GEN (CATERING / CORPORATE)
  // -------------------------------------------------------------------------
  {
    id: "send_details_catering",
    intent: "lead_gen",
    english: "Send your details for catering",
    arabic: "أرسل تفاصيلك للتموين",
    bestPlatforms: ["meta_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
  },
  {
    id: "book_private_event",
    intent: "lead_gen",
    english: "Book a private event",
    arabic: "احجز مناسبة خاصة",
    bestPlatforms: ["google_search", "meta_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
  },
  {
    id: "get_corporate_pdf",
    intent: "lead_gen",
    english: "Get the corporate menu PDF",
    arabic: "احصل على قائمة التموين PDF",
    bestPlatforms: ["meta_feed"],
    funnelStages: ["mofu"],
    fatigue: "low",
  },
  {
    id: "whatsapp_events_team",
    intent: "lead_gen",
    english: "WhatsApp our events team",
    arabic: "واتساب فريق المناسبات",
    bestPlatforms: ["meta_ctwa", "meta_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
  },

  // -------------------------------------------------------------------------
  // DISCOUNT-LED
  // -------------------------------------------------------------------------
  {
    id: "use_code_iftar25",
    intent: "discount_led",
    english: "Use code IFTAR25",
    arabic: "استخدم الكود IFTAR25",
    bestPlatforms: ["meta_feed", "meta_reels", "tiktok_in_feed"],
    funnelStages: ["bofu"],
    fatigue: "moderate",
    notes: "Burns fast — refresh codes every 4-6 weeks",
  },
  {
    id: "show_story_20_off",
    intent: "discount_led",
    english: "Show this story for 20% off",
    arabic: "اعرض هذه القصة لخصم 20٪",
    bestPlatforms: ["meta_stories"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Strong on Stories; physical-presence required (no delivery)",
  },
  {
    id: "first_order_aed30_off",
    intent: "discount_led",
    english: "First order: AED 30 off",
    arabic: "أول طلب: خصم 30 درهم",
    bestPlatforms: ["meta_feed", "meta_reels", "tiktok_in_feed"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Best for delivery acquisition",
  },
  {
    id: "walk_in_with_coupon",
    intent: "discount_led",
    english: "Walk in with this coupon",
    arabic: "تعال بهذا الكوبون",
    bestPlatforms: ["meta_stories"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Foot-traffic measurement",
  },
  {
    id: "free_dessert_with_mains",
    intent: "discount_led",
    english: "Free dessert with mains",
    arabic: "حلوى مجاناً مع الطبق الرئيسي",
    bestPlatforms: ["meta_feed", "meta_reels", "meta_stories"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Industry's most-redeemed offer — 35-50% redemption rate",
  },
  {
    id: "buy_one_second_half_off",
    intent: "discount_led",
    english: "Second main half off",
    arabic: "الطبق الثاني بنص السعر",
    bestPlatforms: ["meta_feed", "meta_reels"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Use this framing instead of 'BOGO entire meal' in MENA — dignified positioning",
  },
  {
    id: "kids_eat_free",
    intent: "discount_led",
    english: "Kids eat free this week",
    arabic: "الأطفال يأكلون مجاناً هذا الأسبوع",
    bestPlatforms: ["meta_feed", "meta_reels"],
    funnelStages: ["bofu"],
    fatigue: "low",
    notes: "Family driver in school holidays",
  },
];

// =============================================================================
// CTA SELECTION RULES — for the AI generator
// =============================================================================

export const ctaSelectionRules = {
  byCampaignType: {
    soft_launch_awareness: ["save_this_post", "tag_who_to_bring", "share_with_foodie"],
    grand_opening_blitz: ["whatsapp_to_reserve", "tap_to_book", "open_till_1am"],
    iftar_fill_house: ["whatsapp_to_reserve", "last_seats_book", "use_code_iftar25"],
    delivery_acquisition: ["order_now_talabat", "first_order_aed30_off", "hot_in_25_min", "delivered_tonight"],
    weekday_reservation_fill: ["whatsapp_to_reserve", "tap_to_book", "see_you_friday"],
    weekend_brunch_hero: ["whatsapp_to_reserve", "tap_to_book"],
    birthday_club: ["drop_by_saved_seat", "free_dessert_with_mains"],
    weather_trigger_delivery: ["delivered_tonight", "hot_in_25_min", "first_order_aed30_off"],
    lto_menu_drop: ["save_this_post", "whatsapp_to_reserve", "last_seats_book"],
    influencer_led_launch: ["use_code_iftar25", "tap_to_book"],
    dormant_reactivation: ["drop_by_saved_seat", "free_dessert_with_mains"],
    catering_corporate_lead_gen: ["send_details_catering", "whatsapp_events_team", "get_corporate_pdf"],
    premium_brand_defense: ["whatsapp_to_reserve", "book_private_event"],
    multi_location_chain: ["whatsapp_to_reserve", "tap_to_book"],
  },
  byGeography: {
    AE: { primary: "whatsapp_to_reserve", currencyOverride: "AED" },
    SA: { primary: "whatsapp_to_reserve", currencyOverride: "SAR", snapAdditional: ["pull_up_tonight"] },
    QA: { primary: "whatsapp_to_reserve", currencyOverride: "QAR" },
    KW: { primary: "whatsapp_to_reserve", currencyOverride: "KWD" },
    BH: { primary: "whatsapp_to_reserve", currencyOverride: "BHD" },
    OM: { primary: "whatsapp_to_reserve", currencyOverride: "OMR" },
  },
} as const;
