import type { HookTemplate } from "./types";

// =============================================================================
// 40 HOOK TEMPLATES — fill-in-the-blank for restaurant ads (Q2 2026)
// =============================================================================
//
// Tag conventions:
//   - bestPlatforms: where this hook performs best
//   - funnelStages: where this hook fits in the funnel
//   - voicingMode: voiced VO / on-screen text / both
//   - fatigue: 2026 saturation level — heavy = use sparingly
//
// The first 1.5-2 seconds determine 65%+ of completion outcomes.

export const hookTemplates: HookTemplate[] = [
  {
    id: "pov_walked_in",
    template: "POV: you walked into [restaurant] and ordered the [dish]",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "both",
    fatigue: "mild",
    notes: "Still works in 2026; pair with 'first bite' archetype",
  },
  {
    id: "if_you_live_in_city",
    template: "If you live in [city], you HAVE to try this",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "both",
    fatigue: "heavy",
    notes: "Soften wording — 'you should know about this' performs better in 2026",
  },
  {
    id: "i_tried_n_dishes",
    template: "I tried [n] [dish] in [city] — this was the best",
    bestPlatforms: ["tiktok_in_feed", "meta_reels", "youtube_shorts"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "voiced",
    fatigue: "low",
    notes: "Listicle still strong; pair with comparison archetype",
  },
  {
    id: "tell_me_without_telling",
    template: "Tell me you've been to [city] without telling me you've been to [city]",
    bestPlatforms: ["tiktok_in_feed"],
    cuisineFits: ["streetfood"],
    funnelStages: ["tofu"],
    voicingMode: "text",
    fatigue: "heavy",
    notes: "Cliché — avoid",
  },
  {
    id: "only_x_in_city",
    template: "The only [cuisine] spot in [city] that [unique angle]",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "both",
    fatigue: "low",
  },
  {
    id: "ramadan_vibes",
    template: "Ramadan 2026 vibes only",
    templateAr: "أجواء رمضان 2026 بس",
    bestPlatforms: ["meta_reels", "meta_stories", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "text",
    fatigue: "seasonal_peak",
    dialect: "bilingual",
  },
  {
    id: "why_everyone_talking",
    template: "Why is everyone in [city] talking about [dish]?",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "both",
    fatigue: "mild",
  },
  {
    id: "n_reasons_to_come_back",
    template: "[Number] reasons to come back to [restaurant]",
    bestPlatforms: ["meta_carousel", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "text",
    fatigue: "low",
    notes: "Listicle save-bait",
  },
  {
    id: "day_n_trying_every",
    template: "Day [n] of trying every [cuisine] spot in [city]",
    bestPlatforms: ["tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "voiced",
    fatigue: "moderate",
    notes: "Series builds momentum — commit to 7+ days",
  },
  {
    id: "things_hit_different",
    template: "Things that just hit different at [restaurant]",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "text",
    fatigue: "heavy",
    notes: "Phrase aging — substitute with 'underrated at' or 'only here'",
  },
  {
    id: "reading_bad_reviews",
    template: "Reading bad reviews of my favorite restaurant",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["bofu"],
    voicingMode: "voiced",
    fatigue: "low",
    notes: "Comedy hook — strong proof-of-quality angle",
  },
  {
    id: "if_x_doesnt_try",
    template: "If [type of person] doesn't try this they're losing",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "both",
    fatigue: "mild",
  },
  {
    id: "ranking_every_dish",
    template: "Ranking every [dish] from [n] [city] spots",
    bestPlatforms: ["tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "voiced",
    fatigue: "low",
  },
  {
    id: "dish_hits_in_neighborhood",
    template: "[Dish] hits different in [neighborhood]",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "text",
    fatigue: "mild",
  },
  {
    id: "what_chef_eats",
    template: "What [chef name] eats at his own restaurant",
    bestPlatforms: ["meta_reels", "youtube_shorts"],
    cuisineFits: ["fine_dining", "premium_casual"],
    funnelStages: ["mofu"],
    voicingMode: "voiced",
    fatigue: "low",
  },
  {
    id: "things_i_wish_i_knew",
    template: "Things I wish I knew before going to [restaurant]",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["bofu"],
    voicingMode: "text",
    fatigue: "low",
    notes: "Save-bait — drives DM shares",
  },
  {
    id: "how_they_make_viral_dish",
    template: "How [restaurant] makes their viral [dish]",
    bestPlatforms: ["meta_reels", "tiktok_in_feed", "youtube_shorts"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "both",
    fatigue: "low",
  },
  {
    id: "asked_chef_what_to_order",
    template: "I asked the chef what to order — here's what he picked",
    bestPlatforms: ["meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "voiced",
    fatigue: "low",
  },
  {
    id: "but_only_dietary_menu",
    template: "[Restaurant] but only the [dietary tag] menu",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["vegan", "halal_certified"],
    funnelStages: ["mofu"],
    voicingMode: "both",
    fatigue: "low",
  },
  {
    id: "suhoor_yes_or_no",
    template: "Suhoor at [restaurant] — yes or no?",
    templateAr: "سحور في [المطعم] - يستاهل ولا لا؟",
    bestPlatforms: ["meta_reels", "meta_stories"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "both",
    fatigue: "seasonal_peak",
    dialect: "bilingual",
    notes: "Ramadan only; the highest-performing MENA hook in season",
  },
  {
    id: "when_residents_tell_you",
    template: "When [city] residents tell you where to eat",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "voiced",
    fatigue: "mild",
  },
  {
    id: "dish_for_price_worth_it",
    template: "[Dish] for [price] in [city] — is it worth it?",
    bestPlatforms: ["tiktok_in_feed", "youtube_shorts"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "voiced",
    fatigue: "low",
    notes: "Value framing strong in inflation-aware 2026",
  },
  {
    id: "tried_most_viral_dish",
    template: "We tried the most viral [dish] in [city]",
    bestPlatforms: ["tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "voiced",
    fatigue: "mild",
  },
  {
    id: "tourist_vs_local",
    template: "What [tourist] vs. [local] orders at [restaurant]",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "both",
    fatigue: "low",
  },
  {
    id: "if_you_dont_youre_doing_wrong",
    template: "If you don't [action] when you eat [dish] you're doing it wrong",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "voiced",
    fatigue: "low",
  },
  {
    id: "everyone_says_overhyped",
    template: "Everyone says [dish] in [city] is overhyped — let's see",
    bestPlatforms: ["tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "voiced",
    fatigue: "low",
  },
  {
    id: "is_unreal",
    template: "The [cuisine] [dish] at [restaurant] is unreal",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "both",
    fatigue: "low",
  },
  {
    id: "show_story_redeem",
    template: "Show this story to redeem [offer]",
    templateAr: "اعرض هذه القصة لاسترداد [العرض]",
    bestPlatforms: ["meta_stories", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["bofu"],
    voicingMode: "text",
    fatigue: "low",
    notes: "Strong direct response; foot-traffic measurement",
  },
  {
    id: "this_is_your_sign",
    template: "This is your sign to try [dish] at [restaurant]",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["bofu"],
    voicingMode: "text",
    fatigue: "heavy",
    notes: "Overused — substitute with 'don't sleep on...' or 'before it sells out...'",
  },
  {
    id: "n_minutes_in_30",
    template: "[n] minutes of food at [restaurant] in 30 seconds",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "text",
    fatigue: "low",
    notes: "Montage-friendly",
  },
  {
    id: "wait_for_it",
    template: "Wait for it… [payoff dish]",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "text",
    fatigue: "mild",
    notes: "Saturated but mechanically still effective",
  },
  {
    id: "ordering_entire_section",
    template: "Ordering the entire [section] of the menu",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["casual", "premium_casual"],
    funnelStages: ["mofu"],
    voicingMode: "voiced",
    fatigue: "low",
  },
  {
    id: "tier_list_edition",
    template: "[Dish] tier list — [restaurant] edition",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["mofu"],
    voicingMode: "voiced",
    fatigue: "low",
  },
  {
    id: "what_i_order_vs_bring",
    template: "What I order vs. what they bring",
    bestPlatforms: ["tiktok_in_feed"],
    cuisineFits: ["casual", "premium_casual"],
    funnelStages: ["mofu"],
    voicingMode: "text",
    fatigue: "mild",
  },
  {
    id: "send_to_whoever_owes",
    template: "Send this to whoever owes you a meal",
    bestPlatforms: ["meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["bofu"],
    voicingMode: "text",
    fatigue: "low",
    notes: "Share-bait — drives the #1 Reels ranking signal",
  },
  {
    id: "its_giving",
    template: "It's giving [adjective] + dish reveal",
    bestPlatforms: ["tiktok_in_feed", "meta_reels"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "text",
    fatigue: "heavy",
    notes: "Gen-Z fatigue — substitute with 'serving [adjective]' or 'this energy is...'",
  },
  {
    id: "for_occasion_yes_no",
    template: "[Restaurant] for [occasion]: [yes/no]",
    bestPlatforms: ["meta_reels", "meta_stories"],
    cuisineFits: ["all"],
    funnelStages: ["bofu"],
    voicingMode: "both",
    fatigue: "low",
  },
  {
    id: "dress_code_wait_time",
    template: "Dress code, wait time, and what to order at [restaurant]",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["fine_dining"],
    funnelStages: ["bofu"],
    voicingMode: "voiced",
    fatigue: "low",
    notes: "Practical save-bait",
  },
  {
    id: "drop_your_favorite",
    template: "[City] residents, drop your favorite [cuisine] spot",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "text",
    fatigue: "mild",
    notes: "Engagement-bait; post organically rather than paid",
  },
  {
    id: "we_arent_gatekeeping",
    template: "We aren't gatekeeping — [restaurant] is the answer",
    bestPlatforms: ["meta_reels", "tiktok_in_feed"],
    cuisineFits: ["all"],
    funnelStages: ["tofu"],
    voicingMode: "text",
    fatigue: "heavy",
    notes: "Phrase tired — avoid",
  },
];

// =============================================================================
// MENA-SPECIFIC HIGH-PERFORMERS
// =============================================================================

export const menaSignatureHooks: Array<{ template: string; templateAr?: string; context: string }> = [
  { template: "Suhoor at [restaurant] — yes or no?", templateAr: "سحور في [المطعم]؟", context: "Ramadan" },
  { template: "Iftar buffet under AED [price] — is it worth it?", templateAr: "بوفيه إفطار بأقل من [السعر] درهم — يستاهل؟", context: "Ramadan" },
  { template: "Ramadan 2026 vibes only", templateAr: "أجواء رمضان 2026 بس", context: "Ramadan" },
  { template: "Best majlis-style dining in [emirate]", templateAr: "أفضل مجلس فاخر في [الإمارة]", context: "Premium Khaleeji" },
  { template: "Where [Khaleeji families] actually eat in [city]", templateAr: "وين العايلة الخليجية تاكل في [المدينة]", context: "Family GCC" },
  { template: "Halal omakase exists and it's in [Dubai/Riyadh]", context: "Premium niche" },
  { template: "Eid family lunch sets under AED [price]", templateAr: "غداء العائلة في العيد بأقل من [السعر] درهم", context: "Eid" },
  { template: "Where in [Riyadh] for [cuisine] when you have only 30 minutes", context: "KSA QSR" },
];

// =============================================================================
// 2026 FATIGUE LIST — phrases the AI should avoid or replace
// =============================================================================

export const fatigue2026 = {
  avoid: [
    "It's giving",
    "Tell me without telling me",
    "Gatekeeping",
    "Things that just hit different",
    "This is your sign",
    "Hits different",
    "Era (as in '[restaurant] era')",
  ],
  substitutes: {
    "It's giving": ["serving", "this energy is", "the vibe is"],
    "Tell me without telling me": ["nobody talks about", "the proof is in"],
    "Gatekeeping": ["the open secret is", "we're sharing"],
    "Things that just hit different": ["only here at", "underrated at"],
    "This is your sign": ["don't sleep on", "before it sells out"],
    "Hits different": ["nothing like it", "made fresh"],
  },
} as const;
